### ISSUE TITLE
Allow disabling using nether portals

### ISSUE THREAD

**Issue by AngrySoundTech** [CivMC/SimpleAdminHacks#10]

**Comment by Diet-Cola** [comment]
SAH already supports disabling nether portals, do we want to specifically disable lighting portals? @wingzero54

**Comment by AngrySoundTech** [comment]
I took a look at the [code for it here](https://github.com/CivMC/SimpleAdminHacks/blob/master/paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/GameTuning.java#L297-L311) and it looks like it would allow players to use portals to travel back to the overworld from the nether instead of completely disabling them

**Comment by Diet-Cola** [comment]
Method below prevents portals being used under any circumstance if its a nether portal
