### ISSUE TITLE
Minecarts & Pistons need management

### ISSUE THREAD

**Issue by psygate** [CivMC/SimpleAdminHacks#24]
SimpleAdminHacks needs limits for minecarts & pistons. See [Thread](https://discord.com/channels/912074050086502470/919348449407815680/989921554106298429)

Related / Same? https://github.com/CivMC/SimpleAdminHacks/issues/2

**Comment by Protonull** [comment]
In terms of minecarts (and presumably boats), you could do something similar to https://github.com/CivClassic/SimpleAdminHacks/pull/89: storing a timestamp in its PDC of when it was placed / last emptied of passengers, then check every so often if a certain amount of time has passed, and if so, the boat/minecart is broken into an item, which can then despawn.

**Comment by psygate** [comment]
https://github.com/CivMC/SimpleAdminHacks/pull/39
https://github.com/CivMC/SimpleAdminHacks/pull/33
