### ISSUE TITLE
SAH constantly throwing players into the void

### ISSUE THREAD

**Issue by wingzero54** [CivMC/SimpleAdminHacks#29]
We have had a recurring issue where players that logout while in a vehicle (especially when the server locks up or crashes), when they login they get teleported into the void.

This is due to SAH's attempt to prevent falling through bedrock: https://github.com/CivMC/SimpleAdminHacks/blob/master/paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/GameTuning.java#L439

I imagine it is something to do with the y-level check and the new -64 y levels. So that anytime a player logs out under y0, especially in a vehicle, SAH things they have fallen into bedrock and teleports them into the void in an attempt to move them out of the bedrock. I do not know if this also occurs above y0, will require testing. 

How I know it is SAH - 
1) server crashed when player was riding donkey
2) player logs in at coordinates inside of tunnel at y-62
3) SimpleAdminHacks registers 'player' falling into the void: Teleported to Location y-66 (which is what _actually_ throws the player into the void

**Comment by Gjum** [comment]
the way I read the code it just puts the player where it already wants to go without enforcing the y limit

possible fixes include:
- change checkForTeleportSpace() to check for y >= minHeight
- change onPlayerMove() to clamp event.getTo() to minHeight before calling tryToTeleportVertically() with it
- change tryToTeleportVertically() to clamp loc.y to minHeight at the very beginning of the method

```java
// while the chunk wasn't loaded clientside, the player fell to y-70
// now the player tells the server "I am moving to y-70"
public void onPlayerMove(PlayerMoveEvent event) {
  if(config.isEnabled() && config.isPreventFallingThroughBedrock() 
      && event.getTo().getY() // -70
        < event.getTo().getWorld().getMinHeight() // -64
      && GameMode.SURVIVAL.equals(event.getPlayer().getGameMode())) {
    TeleportUtil.tryToTeleportVertically(
      event.getPlayer(),
      event.getTo(), // y-70
      "falling into the void");
  }
}
public static boolean tryToTeleportVertically(Player player, Location location, String reason) {
  Location loc = location.clone();
  loc.setX(Math.floor(loc.getX()) + 0.500000D);
  loc.setY(Math.floor(loc.getY()) + 0.02D);
  loc.setZ(Math.floor(loc.getZ()) + 0.500000D);
  // loc is now x.5, -70.02, z.5
  final Location baseLoc = loc.clone();
  final World world = baseLoc.getWorld();
  boolean performTeleport = checkForTeleportSpace(loc);
  // >>> inlined function for readability
    public static boolean checkForTeleportSpace(Location loc) {
      final Block block = loc.getBlock();
      final Material mat = block.getType();
      // y-70 is not solid (it's air below bedrock)
      if (mat.isSolid()) return false;
      final Block above = block.getRelative(BlockFace.UP);
      // y-69 is not solid (it's air below bedrock)
      if (above.getType().isSolid()) return false;
      // all in all, the player's location (below bedrock) is a "valid" teleport space
      return true;
    }
  // <<< end inlined function
  if (!performTeleport) { /* ... skipped */ }
  if (performTeleport) {
    player.setVelocity(new Vector());
    player.teleport(loc);
    SimpleAdminHacks.instance().log(String.format(
      "Player '%s' %s: Teleported to %s",
      player.getName(), reason, loc.toString()));
    return true;
  }
  // remaining code doesn't even run
}
```

**Comment by Diet-Cola** [comment]
This was a very hacky solution for Devoted 3.0, does this really need to even be enabled?

**Comment by wingzero54** [comment]
I can't really think of why it is needed, what situation were you running into on Devoted 3 that you needed to teleport players out of the void?

**Comment by Diet-Cola** [comment]
Might be thinking wrongly of sanity hack

Do we really need to teleport players when we have donum?

**Comment by wingzero54** [comment]
Those two do totally different things, but I agree that best action is probably to just turn this off. I can't think of any reason why it is needed, although we might find out once we turn it off

**Comment by wingzero54** [comment]
https://github.com/CivMC/CivDocker/commit/ea42b74bad479990022dccc0691ca19df4f325ce
