### ISSUE TITLE
/cardinal teleports you out of vehicles

### ISSUE THREAD

**Issue by wingzero54** [CivMC/SimpleAdminHacks#45]
This can cause a player to get thrown under bedrock if they run /cardinal while riding a minecart at bedrock.

**Comment by awoo-civ** [comment]
Ideally it would align boats, not only the player's view.

**Comment by Diet-Cola** [comment]
This might be out of the question until 1.19 as we cannot keep players as passengers while teleporting them without Papers new relative teleport api

**Comment by Aleksey-Terzi** [comment]
Then perhaps disable command while riding?

PS. This command is in Finale, not in SAH.

**Comment by Protonull** [comment]
> PS. This command is in Finale, not in SAH.

It should be a SAH command tbh.
